FROM node:16-alpine
WORKDIR /usr/src/app
ARG PORT=${PORT}
ARG DATABASE_URL=${DATABASE_URL}
ARG MINIO_ENDPOINT=${MINIO_ENDPOINT}
ARG MINIO_ACESS_KEY=${MINIO_ACESS_KEY}
ARG MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
ARG MINIO_BUCKET=${MINIO_BUCKET}
ARG TOKEN=${TOKEN}
ARG CORS_ORIGIN=${CORS_ORIGIN}
ADD . /usr/src/app
RUN npm install
ENV NODE_ENV=production
EXPOSE 3000
CMD [ "npm", "run", "production" ]